=== fun90/fun-validation/target/classes/fun-validation-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ 文件名：jkurrent-validation-1.0.xsd
  ~ 版权：Copyright 2011-2018 Kurrent Tech. Co. Ltd. All Rights Reserved.
  ~
  -->

<xsd:schema
        xmlns="http://www.fun90.com/schema/fun-validation"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:vt="http://www.fun90.com/schema/fun-validation"
        targetNamespace="http://www.fun90.com/schema/fun-validation"
        elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xsd:element name="validation">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="validator" type="validatorType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="properties" type="propertiesType" minOccurs="0" maxOccurs="1">
                    <xsd:unique name="propertyName">
                        <xsd:selector xpath="vt:property"/>
                        <xsd:field xpath="@name"/>
                    </xsd:unique>
                </xsd:element>
                <xsd:element name="rules" type="rulesType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="group" type="groupType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="include" type="inlcudeType" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>

        <xsd:unique name="validatorName">
            <xsd:selector xpath="vt:validator"/>
            <xsd:field xpath="@name"/>
        </xsd:unique>
        <xsd:unique name="rulesId">
            <xsd:selector xpath="vt:rules"/>
            <xsd:field xpath="@id"/>
        </xsd:unique>
        <xsd:unique name="groupId">
            <xsd:selector xpath="vt:group"/>
            <xsd:field xpath="@id"/>
        </xsd:unique>
    </xsd:element>

    <xsd:complexType name="propertiesType">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="property" type="propertyType"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="propertyType">
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="value" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="inlcudeType">
        <xsd:attribute name="resource" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="validatorType">
        <xsd:attribute name="name" type="xsd:ID" use="required"/>
        <xsd:attribute name="class" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="rulesType">
        <xsd:sequence>
            <xsd:element name="rule" type="ruleType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:ID" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="ruleType">
        <xsd:sequence>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="ref" type="xsd:string" use="optional"/>
        <xsd:attribute name="name" type="xsd:string" use="optional"/>
        <xsd:attribute name="message" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="paramType">
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="value" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="groupType">
        <xsd:sequence>
            <xsd:element name="field" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="rule" type="ruleType" minOccurs="0" maxOccurs="unbounded"/>
                    </xsd:sequence>
                    <xsd:attribute name="name" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="extend" type="xsd:string"/>
    </xsd:complexType>

</xsd:schema>

=== fun90/fun-validation/src/test/resources/validation2.xml
<?xml version="1.0" encoding="UTF-8"?>
<validation xmlns="http://www.fun90.com/schema/fun-validation"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.fun90.com/schema/fun-validation http://www.fun90.com/schema/fun-validation/fun-validation-1.0.xsd">

    <group id="user.validate2">
        <!-- 验证字段 -->
        <field name="email">
            <!-- 规则列表 -->
            <rule ref="email2"/>
            <rule name="required" message="邮件必须填写"/>
        </field>

        <field name="id">
            <rule name="match" message="用户ID已被使用">
                <param name="regex" value="^100\d*$"/>
            </rule>
        </field>

        <field name="username">
            <rule name="custom" message="非法的用户名">
                <param name="value" value="admin"/>
            </rule>
        </field>

        <field name="password">
            <rule name="required" message="密码必须填写"/>
            <rule name="min" message="密码至少5个字符">
                <param name="value" value="5"/>
            </rule>
            <rule name="max" message="密码最多20个字符">
                <param name="value" value="20"/>
            </rule>
            <rule name="equals" message="两次密码输入不正确">
                <param name="target" value="passwordOne"/>
            </rule>
        </field>
        <field name="starttime">
            <rule name="timestampLessEqual" message="开始时间不能大于结束时间">
                <param name="target" value="endtime"/>
            </rule>
        </field>
        <field name="endtime">
            <rule name="timestampGreaterEqual" message="结束时间不能小于开始时间">
                <param name="target" value="starttime"/>
            </rule>
        </field>
    </group>
</validation>

=== fun90/fun-validation/src/main/resources/validation-common.xml
<?xml version="1.0" encoding="UTF-8"?>
<validation xmlns="http://www.fun90.com/schema/fun-validation"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.fun90.com/schema/fun-validation http://www.fun90.com/schema/fun-validation/fun-validation-1.0.xsd">
    <validator name="required" class="com.fun90.validation.validators.RequiredValidator"/>
    <validator name="match" class="com.fun90.validation.validators.MatchValidator"/>
    <validator name="between" class="com.fun90.validation.validators.BetweenValidator"/>
    <validator name="min" class="com.fun90.validation.validators.MinValidator"/>
    <validator name="max" class="com.fun90.validation.validators.MaxValidator"/>
    <validator name="equals" class="com.fun90.validation.validators.EqualsValidator"/>
    <validator name="timestampLessEqual"
               class="com.fun90.validation.validators.TimestampLessEqualValidator"/>
    <validator name="timestampGreaterEqual"
               class="com.fun90.validation.validators.TimestampCreaterEqualValidator"/>

    <properties>
        <property name="checkAll" value="true"/>
    </properties>

</validation>
